apiVersion: v1
kind: Namespace
metadata:
  name: tpcp-system
  labels:
    app.kubernetes.io/name: tpcp
    app.kubernetes.io/managed-by: kubectl
    pod-security.kubernetes.io/enforce: restricted
    pod-security.kubernetes.io/audit: restricted
