import { execSync } from 'child_process';
import * as path from 'path';
import { AgentIdentityManager } from '../src/security/crypto';

describe('Cross-Language Compatibility', () => {
  it('should verify signatures generated by the Python SDK', () => {
    // Execute the python script
    const pyScriptPath = path.join(__dirname, 'generate_fixture.py');
    const output = execSync(`python "${pyScriptPath}"`).toString();
    const data = JSON.parse(output);
    
    // Verify using TypeScript SDK
    const isValid = AgentIdentityManager.verifySignature(data.pub, data.sig, data.payload);
    expect(isValid).toBe(true);
  });
});
