apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: tpcp-relay-pdb
  namespace: tpcp-system
spec:
  minAvailable: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: tpcp-relay
