apiVersion: v1
kind: ServiceAccount
metadata:
  name: tpcp-relay
  namespace: tpcp-system
  labels:
    app.kubernetes.io/name: tpcp-relay
    app.kubernetes.io/component: relay
automountServiceAccountToken: false
