name: Java Tests
on:
  push:
    paths: ['tpcp-java/**']
  pull_request:
    paths: ['tpcp-java/**']
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - run: cd tpcp-java && mvn test
